version: "3.8"
services:
  coderunner:
    image: coc0a25/coderunner:0.1
    container_name: coderunner
    restart: always
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    volumes:
      - ./log/compile:/log/compile
      - ./log/run:/log/run
      - ./log/server:/log/server
    ports:
    - "0.0.0.0:8900:3000"
